/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ivyteam.ivy.visualvm.view;

/**
 *
 * @author thnghia
 */
public class ExternalDbErrorsPanel extends javax.swing.JPanel {

  /**
   * Creates new form ExternalDbPanel
   */
  public ExternalDbErrorsPanel() {
    initComponents();
    tableErrors.setCellEditor(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    btnRefresh = new javax.swing.JButton();
    emptyLabel = new javax.swing.JLabel();
    jSplitPane1 = new javax.swing.JSplitPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    tableErrors = new javax.swing.JTable();
    errorDetailsTabbedPane = new javax.swing.JTabbedPane();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtStacktrace = new javax.swing.JTextArea();
    jScrollPane3 = new javax.swing.JScrollPane();
    txtSQL = new javax.swing.JTextArea();

    setBackground(new java.awt.Color(255, 255, 255));
    setLayout(new java.awt.GridBagLayout());

    org.openide.awt.Mnemonics.setLocalizedText(btnRefresh, org.openide.util.NbBundle.getMessage(ExternalDbErrorsPanel.class, "ExternalDbErrorsPanel.btnRefresh.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btnRefresh, gridBagConstraints);

    org.openide.awt.Mnemonics.setLocalizedText(emptyLabel, org.openide.util.NbBundle.getMessage(ExternalDbErrorsPanel.class, "ExternalDbErrorsPanel.emptyLabel.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(emptyLabel, gridBagConstraints);

    jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
    jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jSplitPane1.setDividerLocation(150);
    jSplitPane1.setDividerSize(3);
    jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

    jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

    tableErrors.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"26/5/2014 14:20:30", "app/env/dbconfig", "12456", "The error message"},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Time", "DB config", "Process element ID", "Error message"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tableErrors);

    jSplitPane1.setLeftComponent(jScrollPane1);

    jScrollPane2.setBorder(null);

    txtStacktrace.setEditable(false);
    txtStacktrace.setColumns(20);
    txtStacktrace.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
    txtStacktrace.setRows(5);
    txtStacktrace.setText(org.openide.util.NbBundle.getMessage(ExternalDbErrorsPanel.class, "ExternalDbErrorsPanel.txtStacktrace.text")); // NOI18N
    jScrollPane2.setViewportView(txtStacktrace);

    errorDetailsTabbedPane.addTab(org.openide.util.NbBundle.getMessage(ExternalDbErrorsPanel.class, "ExternalDbErrorsPanel.jScrollPane2.TabConstraints.tabTitle"), jScrollPane2); // NOI18N

    jScrollPane3.setBorder(null);

    txtSQL.setEditable(false);
    txtSQL.setColumns(20);
    txtSQL.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
    txtSQL.setRows(5);
    txtSQL.setText(org.openide.util.NbBundle.getMessage(ExternalDbErrorsPanel.class, "ExternalDbErrorsPanel.txtSQL.text")); // NOI18N
    jScrollPane3.setViewportView(txtSQL);

    errorDetailsTabbedPane.addTab(org.openide.util.NbBundle.getMessage(ExternalDbErrorsPanel.class, "ExternalDbErrorsPanel.jScrollPane3.TabConstraints.tabTitle"), jScrollPane3); // NOI18N

    jSplitPane1.setRightComponent(errorDetailsTabbedPane);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(jSplitPane1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnRefresh;
  private javax.swing.JLabel emptyLabel;
  private javax.swing.JTabbedPane errorDetailsTabbedPane;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTable tableErrors;
  private javax.swing.JTextArea txtSQL;
  private javax.swing.JTextArea txtStacktrace;
  // End of variables declaration//GEN-END:variables
}
