/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ivyteam.ivy.visualvm.view;

import ch.ivyteam.ivy.visualvm.ContentProvider;
import ch.ivyteam.ivy.visualvm.model.IvyLicenseInfo;
import ch.ivyteam.ivy.visualvm.util.DataUtils;
import java.text.MessageFormat;

/**
 *
 * @author thtam
 */
@SuppressWarnings("PMD.SingularField")
public class LicenseInformationPanel extends javax.swing.JPanel {

  private final IvyLicenseInfo fLicenseInfo;
  private static final long MILISECONDS_IN_ONE_SECOND = 1000;
  private static final long MILISECONDS_IN_ONE_MINUTE = 60 * MILISECONDS_IN_ONE_SECOND;
  private static final long MILISECONDS_IN_ONE_HOUR = 60 * MILISECONDS_IN_ONE_MINUTE;
  public static final long MILISECONDS_IN_ONE_DAY = 24 * MILISECONDS_IN_ONE_HOUR;

  private static final String WARNING_ICON_PATH = "/resources/icons/license_warning.png";
  private static final String ERROR_ICON_PATH = "/resources/icons/license_error.png";
  private static final String WARNING_COLOR = "#EF6C00";
  private static final String ERROR_COLOR = "#FF0000";
  private static final String TABLE_START = "<table border='0' celspacing='5' celpadding='0'>";
  private static final String TABLE_END = "</table>";
  private static final String TR_TD_START = "<tr><td>";
  private static final String TR_TD_START_WITH_NO_WRAP = "<tr style='white-space: nowrap;'><td>";
  private static final String TD_TR_END = "</td></tr>";
  private static final String TD_START = "<td>";
  private static final String TD_END = "</td>";

  private static final char CHAR_COLON = ':';
  private static final char CHAR_SPACE = ' ';
  private static final String CONCURRENT_USERS_LIMIT = ContentProvider.get("ConcurrentUsersLimit");
  public static final String NAMED_USERS_LIMIT = ContentProvider.get("NamedUsersLimit");
  public static final String ELEMENTS_LIMIT = ContentProvider.get("ElementsLimit");
  public static final String SUPPORTS_RIA = ContentProvider.get("SupportsRIA");
  public static final String EXPIRES = ContentProvider.get("Expires");
  public static final String VALID_FROM = ContentProvider.get("ValidFrom");
  public static final String VERSION = ContentProvider.get("Version");
  public static final String HOST_NAME = ContentProvider.get("HostName");
  public static final String INDIVIDUAL = ContentProvider.get("Individual");
  public static final String ORGANIZATION = ContentProvider.get("Organization");

  private static final String EXPIRE_IN_30_DAYS_WARNING
          = ContentProvider.getFormatted("ExpireIn30DaysWarning");
  private static final String EXPIRED_WARNING
          = ContentProvider.getFormatted("ExpiredWarning");
  private static final String USERS_80_PERCENT_EXCEEDED_WARNING
          = ContentProvider.getFormatted("Exceed80PerCentOfUsersWarning");
  private static final String USERS_90_PERCENT_EXCEEDED_WARNING
          = ContentProvider.getFormatted("Exceed90PerCentOfUsersWarning");
  private static final String USERS_EXCEEDED_WARNING
          = ContentProvider.getFormatted("ExceedUsersWarning");
  private static final String SESSIONS_90_PERCENT_EXCEEDED_WARNING
          = ContentProvider.getFormatted("Exceed90PerCentOfSessionsWarning");
  private static final String SESSIONS_EXCEEDED_WARNING
          = ContentProvider.getFormatted("ExceedSessionsWarning");
  private static final String SESSIONS_150_PERCENT_EXCEEDED_WARNING
          = ContentProvider.getFormatted("Exceed150PercentOfSessionsWarning");

  private int fNamedUsers;
  private int fConcurrentUsers;
  private long fRemainingTime = Long.MAX_VALUE;

  public LicenseInformationPanel(IvyLicenseInfo licenseInfo) {
    initComponents();
    fLicenseInfo = licenseInfo;
  }

  /*
   * CHECKSTYLE:OFF
   */
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings({"unchecked", "PMD"})
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jScrollPane2 = new javax.swing.JScrollPane();
    htmlLabelPanel1 = new ch.ivyteam.ivy.visualvm.view.HtmlLabelPanel();

    setBackground(new java.awt.Color(255, 255, 255));
    setLayout(new java.awt.GridBagLayout());

    jScrollPane2.setBorder(null);
    jScrollPane2.setViewportView(htmlLabelPanel1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(jScrollPane2, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private ch.ivyteam.ivy.visualvm.view.HtmlLabelPanel htmlLabelPanel1;
  private javax.swing.JScrollPane jScrollPane2;
  // End of variables declaration//GEN-END:variables
  /*
   * CHECKSTYLE:ON
   */

  public void setLicenseData(long remainingTime, int namedUsers, int concurrentUsers) {
    fRemainingTime = remainingTime;
    fNamedUsers = namedUsers;
    fConcurrentUsers = concurrentUsers;
    if (fLicenseInfo != null) {
      htmlLabelPanel1.setText(toHTMLString());
    }
  }

  public String toHTMLString() {
    StringBuilder html = new StringBuilder("<html><body style=\"font-family:tahoma;font-size:11\">");
    appendExpireWarning(html);
    appendUsersLimitWarning(html);
    appendSessionsLimitWarning(html);

    html.append(TABLE_START);
    appendStringValue(html);
    appendNumberValue(html);

    html.append(TABLE_END);
    html.append("</body></html>");
    return html.toString();
  }

  private void appendValue(StringBuilder html, String label, Object value) {
    html.append(TR_TD_START_WITH_NO_WRAP)
            .append(label)
            .append(CHAR_COLON)
            .append(CHAR_SPACE)
            .append(TD_END)
            .append(TD_START)
            .append(value.toString())
            .append(TD_TR_END);
  }

  private void appendStringValue(StringBuilder html) {
    if (fLicenseInfo.getLicenseeOrganisation() != null) {
      appendValue(html, ORGANIZATION, fLicenseInfo.getLicenseeOrganisation());
    }
    if (fLicenseInfo.getLicenseeIndividual() != null) {
      appendValue(html, INDIVIDUAL, fLicenseInfo.getLicenseeIndividual());
    }
    if (fLicenseInfo.getHostName() != null) {
      appendValue(html, HOST_NAME, fLicenseInfo.getHostName());
    }
    if (fLicenseInfo.getLicenseKeyVersion() != null) {
      appendValue(html, VERSION, fLicenseInfo.getLicenseKeyVersion().replace("xpertline/", ""));
    }
    if (fLicenseInfo.getLicenseValidFrom() != null) {
      appendValue(html, VALID_FROM, DataUtils.dateToString(fLicenseInfo.getLicenseValidFrom()));
    }
    if (fLicenseInfo.getLicenseValidUntil() != null) {
      appendValue(html, EXPIRES, DataUtils.dateToString(fLicenseInfo.getLicenseValidUntil()));
    }
    String logicString = fLicenseInfo.isServerRIA() ? ContentProvider.get("Yes") : ContentProvider.get("No");
    appendValue(html, SUPPORTS_RIA, logicString);
  }

  private void appendNumberValue(StringBuilder html) {
    if (fLicenseInfo.getServerElementsLimit() > 0) {
      appendValue(html, ELEMENTS_LIMIT, fLicenseInfo.getServerElementsLimit());
    }
    if (fLicenseInfo.getServerUsersLimit() > 0) {
      appendValue(html, NAMED_USERS_LIMIT, fLicenseInfo.getServerUsersLimit());
    }
    if (fLicenseInfo.getServerSessionsLimit() > 0) {
      appendValue(html, CONCURRENT_USERS_LIMIT, fLicenseInfo.getServerSessionsLimit());
    }
  }

  private void appendSessionsLimitWarning(StringBuilder html) {
    final int serverSessionsLimit = fLicenseInfo.getServerSessionsLimit();
    if (serverSessionsLimit > 0) {
      String warningMsg = null;
      String iconPath = WARNING_ICON_PATH;
      String color = WARNING_COLOR;
      int threshold90 = (int) Math.floor(serverSessionsLimit * 0.9);
      int threshold150 = (int) Math.floor(serverSessionsLimit * 1.5);
      if (fConcurrentUsers >= threshold90 && fConcurrentUsers <= serverSessionsLimit) {
        warningMsg = SESSIONS_90_PERCENT_EXCEEDED_WARNING;
      } else if (fConcurrentUsers > serverSessionsLimit
              && fConcurrentUsers < threshold150) {
        warningMsg = SESSIONS_EXCEEDED_WARNING;
        color = ERROR_COLOR;
        iconPath = ERROR_ICON_PATH;
      } else if (fConcurrentUsers >= threshold150) {
        warningMsg = SESSIONS_150_PERCENT_EXCEEDED_WARNING;
        color = ERROR_COLOR;
        iconPath = ERROR_ICON_PATH;
      }
      if (warningMsg == null) {
        return;
      }
      appendWarning(iconPath, warningMsg, color, html);
    }
  }

  private void appendUsersLimitWarning(StringBuilder html) {
    final int serverUsersLimit = fLicenseInfo.getServerUsersLimit();
    if (serverUsersLimit > 0) {
      String warningMsg = null;
      String iconPath = WARNING_ICON_PATH;
      String color = WARNING_COLOR;
      int threshold80 = (int) Math.floor(serverUsersLimit * 0.8);
      int threshold90 = (int) Math.floor(serverUsersLimit * 0.9);
      if (fNamedUsers >= threshold80 && fNamedUsers < threshold90) {
        warningMsg = USERS_80_PERCENT_EXCEEDED_WARNING;
      } else if (fNamedUsers >= threshold90 && fNamedUsers < serverUsersLimit) {
        warningMsg = USERS_90_PERCENT_EXCEEDED_WARNING;
        color = ERROR_COLOR;
        iconPath = ERROR_ICON_PATH;
      } else if (fNamedUsers >= serverUsersLimit) {
        warningMsg = USERS_EXCEEDED_WARNING;
        color = ERROR_COLOR;
        iconPath = ERROR_ICON_PATH;
      }
      if (warningMsg == null) {
        return;
      }
      appendWarning(iconPath, warningMsg, color, html);
    }
  }

  private void appendExpireWarning(StringBuilder html) {
    if (fLicenseInfo.getLicenseValidUntil() != null) {
      String iconPath = null;
      String warningMsg = null;
      String color = WARNING_COLOR;
      String expireDateString = DataUtils.dateToString(fLicenseInfo.getLicenseValidUntil());

      if (isLicenseError()) {
        warningMsg = MessageFormat.format(EXPIRED_WARNING, expireDateString);
        color = ERROR_COLOR;
        iconPath = ERROR_ICON_PATH;
      } else if (isLicenseWarning()) {
        warningMsg = MessageFormat.format(EXPIRE_IN_30_DAYS_WARNING, expireDateString);
        iconPath = WARNING_ICON_PATH;
      }

      if (warningMsg == null) {
        return;
      }
      appendWarning(iconPath, warningMsg, color, html);
    }
  }

  private void appendWarning(String iconPath, String warningMsg, String color, StringBuilder html) {
    String iconTag = createIconTag(iconPath);
    String htmlWarningMsg = createFontTag(warningMsg, color);
    html.append(TABLE_START)
            .append(TR_TD_START)
            .append(iconTag)
            .append(TD_END)
            .append(TD_START)
            .append(htmlWarningMsg)
            .append(TD_TR_END)
            .append(TABLE_END);
  }

  private boolean isLicenseWarning() {
    return fRemainingTime < 30 * LicenseInformationPanel.MILISECONDS_IN_ONE_DAY;
  }

  private boolean isLicenseError() {
    return fRemainingTime <= 0;
  }

  private String createFontTag(String message, String color) {
    return "<font color='" + color + "'>" + message + "</font>";
  }

  private String createIconTag(String iconPath) {
    return "<img src='" + getClass().getResource(iconPath) + "'>";
  }

}
