/*
 * To change this template, choose Tools | Templates and open the template in the editor.
 */
package ch.ivyteam.ivy.visualvm.chart;

import ch.ivyteam.ivy.visualvm.mbeans.IMAttributeBrowser;
import ch.ivyteam.ivy.visualvm.mbeans.IMBeanBrowser;
import javax.management.MBeanServerConnection;
import javax.swing.DefaultListModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//ch.ivyteam.ivy.visualvm//NewMChartDialog//EN", autostore = false)
@TopComponent.Description(preferredID = "NewMChartDialogTopComponent",
        // iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "bottomSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "ch.ivyteam.ivy.visualvm.NewMChartDialogTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_NewMChartDialogAction", preferredID
        = "NewMChartDialogTopComponent")
@Messages({"CTL_NewMChartDialogAction=NewMChartDialog",
  "CTL_NewMChartDialogTopComponent=NewMChartDialog Window",
  "HINT_NewMChartDialogTopComponent=This is a NewMChartDialog window"})
public final class NewMChartTopComponent extends TopComponent {

  private IMAttributeBrowser mAttributeBrowser;
  private IMBeanBrowser mBeanBrowser;
  private MBeanServerConnection fMBeanServerConnection;

  public NewMChartTopComponent() {
    initComponents();
    setName(Bundle.CTL_NewMChartDialogTopComponent());
    setToolTipText(Bundle.HINT_NewMChartDialogTopComponent());
    series.setModel(new DefaultListModel());

  }

  public void setMBeanServerConnection(MBeanServerConnection mBeanServerConnection) {
    fMBeanServerConnection = mBeanServerConnection;
  }

  /* CHECKSTYLE:OFF */
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed"
  // desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    chartTitleLabel = new javax.swing.JLabel();
    chartTitle = new javax.swing.JTextField();
    xAxisLabel = new javax.swing.JLabel();
    xAxisDescription = new javax.swing.JTextField();
    yAxisLabel = new javax.swing.JLabel();
    yAxisDescription = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    series = new javax.swing.JList();
    jLabel1 = new javax.swing.JLabel();
    seriesLabel = new javax.swing.JLabel();
    addButton = new javax.swing.JButton();
    removeButton = new javax.swing.JButton();
    editButton = new javax.swing.JButton();
    upButton = new javax.swing.JButton();
    downButton = new javax.swing.JButton();

    org.openide.awt.Mnemonics.setLocalizedText(chartTitleLabel,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.chartTitleLabel.text")); // NOI18N

    chartTitle.setText(org.openide.util.NbBundle.getMessage(
            NewMChartTopComponent.class,
            "NewMChartTopComponent.chartTitle.text")); // NOI18N
    chartTitle.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chartTitleActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(xAxisLabel,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.xAxisLabel.text")); // NOI18N

    xAxisDescription.setText(org.openide.util.NbBundle.getMessage(
            NewMChartTopComponent.class,
            "NewMChartTopComponent.xAxisDescription.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(yAxisLabel,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.yAxisLabel.text")); // NOI18N

    yAxisDescription.setText(org.openide.util.NbBundle.getMessage(
            NewMChartTopComponent.class,
            "NewMChartTopComponent.yAxisDescription.text")); // NOI18N

    jScrollPane1.setViewportView(series);

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.jLabel1.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(seriesLabel,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.seriesLabel.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(addButton,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.addButton.text")); // NOI18N
    addButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addButtonActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(removeButton,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.removeButton.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(editButton,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.editButton.text")); // NOI18N
    editButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        editButtonActionPerformed(evt);
      }
    });

    org.openide.awt.Mnemonics.setLocalizedText(upButton,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.upButton.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(downButton,
            org.openide.util.NbBundle.getMessage(
                    NewMChartTopComponent.class,
                    "NewMChartTopComponent.downButton.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                    layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(
                                    layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                    layout.createSequentialGroup()
                                                            .addGroup(
                                                                    layout.createParallelGroup(
                                                                            javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(
                                                                                    xAxisLabel)
                                                                            .addComponent(
                                                                                    chartTitleLabel))
                                                            .addPreferredGap(
                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(
                                                                    layout.createParallelGroup(
                                                                            javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(
                                                                                    chartTitle,
                                                                                    javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addComponent(
                                                                                    xAxisDescription)))
                                            .addGroup(
                                                    layout.createSequentialGroup()
                                                            .addComponent(
                                                                    yAxisLabel)
                                                            .addPreferredGap(
                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(
                                                                    yAxisDescription))
                                            .addGroup(
                                                    layout.createSequentialGroup()
                                                            .addComponent(
                                                                    seriesLabel)
                                                            .addGroup(
                                                                    layout.createParallelGroup(
                                                                            javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(
                                                                                    layout.createSequentialGroup()
                                                                                            .addGap(122,
                                                                                                    122,
                                                                                                    122)
                                                                                            .addComponent(
                                                                                                    jLabel1)
                                                                                            .addGap(0,
                                                                                                    0,
                                                                                                    Short.MAX_VALUE))
                                                                            .addGroup(
                                                                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                    layout.createSequentialGroup()
                                                                                            .addGap(61,
                                                                                                    61,
                                                                                                    61)
                                                                                            .addComponent(
                                                                                                    jScrollPane1,
                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                    385,
                                                                                                    Short.MAX_VALUE)
                                                                                            .addPreferredGap(
                                                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                            .addGroup(
                                                                                                    layout.createParallelGroup(
                                                                                                            javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                            false)
                                                                                                            .addComponent(
                                                                                                                    removeButton,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    Short.MAX_VALUE)
                                                                                                            .addComponent(
                                                                                                                    addButton,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    Short.MAX_VALUE)
                                                                                                            .addComponent(
                                                                                                                    editButton,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    Short.MAX_VALUE)
                                                                                                            .addComponent(
                                                                                                                    upButton,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    Short.MAX_VALUE)
                                                                                                            .addComponent(
                                                                                                                    downButton,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                    Short.MAX_VALUE))))))
                            .addContainerGap()));
    layout.setVerticalGroup(layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                    layout.createSequentialGroup()
                            .addContainerGap(
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE)
                            .addGroup(
                                    layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(chartTitleLabel)
                                            .addComponent(
                                                    chartTitle,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(
                                    layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(
                                                    xAxisDescription,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(xAxisLabel))
                            .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(
                                    layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(yAxisLabel)
                                            .addComponent(
                                                    yAxisDescription,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(
                                    layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(
                                                    jScrollPane1,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    149,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seriesLabel)
                                            .addGroup(
                                                    layout.createSequentialGroup()
                                                            .addComponent(
                                                                    addButton)
                                                            .addPreferredGap(
                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(
                                                                    removeButton)
                                                            .addPreferredGap(
                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(
                                                                    editButton)
                                                            .addPreferredGap(
                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(
                                                                    upButton)
                                                            .addPreferredGap(
                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(
                                                                    downButton)))
                            .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)));
  }// </editor-fold>//GEN-END:initComponents

  private void addButtonActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_addButtonActionPerformed
  {// GEN-HEADEREND:event_addButtonActionPerformed
    NewMSerieTopComponent newSerie = new NewMSerieTopComponent();
    newSerie.setMBeanServerConnection(fMBeanServerConnection);
    NotifyDescriptor descriptor = new NotifyDescriptor(newSerie,
            "Add Chart Serie", NotifyDescriptor.OK_CANCEL_OPTION,
            NotifyDescriptor.PLAIN_MESSAGE, null,
            NotifyDescriptor.YES_OPTION);

    if (DialogDisplayer.getDefault().notify(descriptor) == NotifyDescriptor.OK_OPTION) {
      ((DefaultListModel) series.getModel()).addElement(newSerie
              .getSerieDataSource());
    }
  }// GEN-LAST:event_addButtonActionPerformed

  private void editButtonActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_editButtonActionPerformed
  {// GEN-HEADEREND:event_editButtonActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_editButtonActionPerformed

  private void chartTitleActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_chartTitleActionPerformed
  {// GEN-HEADEREND:event_chartTitleActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_chartTitleActionPerformed

  public MChartDataSource getChartDataSource() {
    MChartDataSource chartDataSource = new MChartDataSource(
            chartTitle.getText(), xAxisDescription.getText(),
            yAxisDescription.getText());
    DefaultListModel model = (DefaultListModel) series.getModel();
    for (int pos = 0; pos < model.size(); pos++) {
      chartDataSource
              .addSerie((MSerieDataSource) model.getElementAt(pos));
    }
    return chartDataSource;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addButton;
  private javax.swing.JTextField chartTitle;
  private javax.swing.JLabel chartTitleLabel;
  private javax.swing.JButton downButton;
  private javax.swing.JButton editButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton removeButton;
  private javax.swing.JList series;
  private javax.swing.JLabel seriesLabel;
  private javax.swing.JButton upButton;
  private javax.swing.JTextField xAxisDescription;
  private javax.swing.JLabel xAxisLabel;
  private javax.swing.JTextField yAxisDescription;
  private javax.swing.JLabel yAxisLabel;

  // End of variables declaration//GEN-END:variables
  /* CHECKSTYLE:ON */
  @Override
  public void componentOpened() {
    // TODO add custom code on component opening
  }

  @Override
  public void componentClosed() {
    // TODO add custom code on component closing
  }

  void writeProperties(java.util.Properties p) {
    // better to version settings since initial version as advocated at
    // http://wiki.apidesign.org/wiki/PropertyFiles
    p.setProperty("version", "1.0");
    // TODO store your settings
  }

  void readProperties(java.util.Properties p) {
    String version = p.getProperty("version");
    // TODO read your settings according to their version
  }

}
