/*
 * To change this template, choose Tools | Templates and open the template in the editor.
 */
package ch.ivyteam.ivy.visualvm.chart;

import ch.ivyteam.ivy.visualvm.MUtil;
import javax.management.MBeanServerConnection;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//ch.ivyteam.ivy.visualvm.chart//NewMSerieTopComponent//EN", autostore = false)
@TopComponent.Description(preferredID = "NewMSerieTopComponentTopComponent",
        // iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "bottomSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "ch.ivyteam.ivy.visualvm.chart.NewMSerieTopComponentTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_NewMSerieTopComponentAction", preferredID
        = "NewMSerieTopComponentTopComponent")
@Messages({"CTL_NewMSerieTopComponentAction=NewMSerieTopComponent",
  "CTL_NewMSerieTopComponentTopComponent=NewMSerieTopComponent Window",
  "HINT_NewMSerieTopComponentTopComponent=This is a NewMSerieTopComponent window"})
public final class NewMSerieTopComponent extends TopComponent {

  public NewMSerieTopComponent() {
    initComponents();
    setName(Bundle.CTL_NewMSerieTopComponentTopComponent());
    setToolTipText(Bundle.HINT_NewMSerieTopComponentTopComponent());
  }

  void setMBeanServerConnection(MBeanServerConnection serverConnection) {
    value.setMBeanServerConnection(serverConnection);
    count.setMBeanServerConnection(serverConnection);
  }

  void setMSerieDataSource(MSerieDataSource serieDataSource) {
    serie.setText(serieDataSource.getSerie());
    switch (serieDataSource.getStyle()) {
      case LINE:
        styleLine.setSelected(true);
        break;
      case FILLED:
        styleFill.setSelected(true);
        break;
      case LINE_FILLED:
        styleLineFill.setSelected(true);
        break;
    }
  }

  MSerieDataSource getSerieDataSource() {
    if (valueKind.isSelected()) {
      return new MAttributeDataSource(serie.getText(), 1L,
              getSerieStyle(), MUtil.createObjectName(value
                      .getMBeanName()), value.getAttribute());
    } else if (deltaKind.isSelected()) {
      return new MDeltaAttributeDataSource(serie.getText(), 1L,
              getSerieStyle(), MUtil.createObjectName(value
                      .getMBeanName()), value.getAttribute());
    } else if (meanKind.isSelected()) {
      MSerieDataSource valueDs = new MAttributeDataSource(
              serie.getText(), 1L, getSerieStyle(),
              MUtil.createObjectName(value.getMBeanName()),
              value.getAttribute());
      MSerieDataSource countDs = new MAttributeDataSource(
              serie.getText(), 1L, getSerieStyle(),
              MUtil.createObjectName(count.getMBeanName()),
              count.getAttribute());
      return new MMeanDataSource(serie.getText(), getSerieStyle(),
              valueDs, countDs);
    } else {
      MSerieDataSource valueDs = new MDeltaAttributeDataSource(
              serie.getText(), 1L, getSerieStyle(),
              MUtil.createObjectName(value.getMBeanName()),
              value.getAttribute());
      MSerieDataSource countDs = new MDeltaAttributeDataSource(
              serie.getText(), 1L, getSerieStyle(),
              MUtil.createObjectName(count.getMBeanName()),
              count.getAttribute());
      return new MMeanDataSource(serie.getText(), getSerieStyle(),
              valueDs, countDs);
    }
  }

  SerieStyle getSerieStyle() {
    if (styleLine.isSelected()) {
      return SerieStyle.LINE;
    } else if (styleFill.isSelected()) {
      return SerieStyle.FILLED;
    } else {
      return SerieStyle.LINE_FILLED;
    }
  }

  /* CHECKSTYLE:OFF */
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed"
  // desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    style = new javax.swing.ButtonGroup();
    kind = new javax.swing.ButtonGroup();
    serieLabel = new javax.swing.JLabel();
    serie = new javax.swing.JTextField();
    styleLabel = new javax.swing.JLabel();
    styleLine = new javax.swing.JRadioButton();
    styleFill = new javax.swing.JRadioButton();
    styleLineFill = new javax.swing.JRadioButton();
    valueKindLabel = new javax.swing.JLabel();
    valueKind = new javax.swing.JRadioButton();
    deltaKind = new javax.swing.JRadioButton();
    meanKind = new javax.swing.JRadioButton();
    deltaMeanKind = new javax.swing.JRadioButton();
    value = new ch.ivyteam.ivy.visualvm.mbeans.MBeanAttributeChooserPanel();
    count = new ch.ivyteam.ivy.visualvm.mbeans.MBeanAttributeChooserPanel();

    org.openide.awt.Mnemonics.setLocalizedText(serieLabel,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.serieLabel.text")); // NOI18N

    serie.setText(org.openide.util.NbBundle
            .getMessage(NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.serie.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(styleLabel,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.styleLabel.text")); // NOI18N

    style.add(styleLine);
    styleLine.setSelected(true);
    org.openide.awt.Mnemonics.setLocalizedText(styleLine,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.styleLine.text")); // NOI18N
    styleLine.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        styleLineActionPerformed(evt);
      }
    });

    style.add(styleFill);
    org.openide.awt.Mnemonics.setLocalizedText(styleFill,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.styleFill.text")); // NOI18N

    style.add(styleLineFill);
    org.openide.awt.Mnemonics.setLocalizedText(styleLineFill,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.styleLineFill.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(valueKindLabel,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.valueKindLabel.text")); // NOI18N

    kind.add(valueKind);
    valueKind.setSelected(true);
    org.openide.awt.Mnemonics.setLocalizedText(valueKind,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.valueKind.text")); // NOI18N
    valueKind.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        valueKindActionPerformed(evt);
      }
    });

    kind.add(deltaKind);
    org.openide.awt.Mnemonics.setLocalizedText(deltaKind,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.deltaKind.text")); // NOI18N
    deltaKind.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deltaKindActionPerformed(evt);
      }
    });

    kind.add(meanKind);
    org.openide.awt.Mnemonics.setLocalizedText(meanKind,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.meanKind.text")); // NOI18N
    meanKind.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        meanKindActionPerformed(evt);
      }
    });

    kind.add(deltaMeanKind);
    org.openide.awt.Mnemonics.setLocalizedText(deltaMeanKind,
            org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.deltaMeanKind.text")); // NOI18N
    deltaMeanKind.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deltaMeanKindActionPerformed(evt);
      }
    });

    value.setBorder(javax.swing.BorderFactory
            .createTitledBorder(org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.value.border.title"))); // NOI18N

    count.setBorder(javax.swing.BorderFactory
            .createTitledBorder(org.openide.util.NbBundle.getMessage(
                    NewMSerieTopComponent.class,
                    "NewMSerieTopComponent.count.border.title"))); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                    layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(
                                    layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                    layout.createSequentialGroup()
                                                            .addGroup(
                                                                    layout.createParallelGroup(
                                                                            javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addGroup(
                                                                                    layout.createSequentialGroup()
                                                                                            .addGroup(
                                                                                                    layout.createParallelGroup(
                                                                                                            javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                            .addComponent(
                                                                                                                    valueKindLabel)
                                                                                                            .addComponent(
                                                                                                                    styleLabel)
                                                                                                            .addComponent(
                                                                                                                    serieLabel))
                                                                                            .addPreferredGap(
                                                                                                    javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                            .addGroup(
                                                                                                    layout.createParallelGroup(
                                                                                                            javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                            .addComponent(
                                                                                                                    serie,
                                                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                    325,
                                                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                            .addGroup(
                                                                                                                    layout.createSequentialGroup()
                                                                                                                            .addGroup(
                                                                                                                                    layout.createParallelGroup(
                                                                                                                                            javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                            .addComponent(
                                                                                                                                                    valueKind)
                                                                                                                                            .addComponent(
                                                                                                                                                    styleLine))
                                                                                                                            .addPreferredGap(
                                                                                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                            .addGroup(
                                                                                                                                    layout.createParallelGroup(
                                                                                                                                            javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                            .addGroup(
                                                                                                                                                    layout.createSequentialGroup()
                                                                                                                                                            .addComponent(
                                                                                                                                                                    deltaKind)
                                                                                                                                                            .addPreferredGap(
                                                                                                                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                            .addComponent(
                                                                                                                                                                    meanKind)
                                                                                                                                                            .addPreferredGap(
                                                                                                                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                            .addComponent(
                                                                                                                                                                    deltaMeanKind))
                                                                                                                                            .addGroup(
                                                                                                                                                    layout.createSequentialGroup()
                                                                                                                                                            .addComponent(
                                                                                                                                                                    styleFill)
                                                                                                                                                            .addPreferredGap(
                                                                                                                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                            .addComponent(
                                                                                                                                                                    styleLineFill))))))
                                                                            .addComponent(
                                                                                    value,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    384,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(0,
                                                                    0,
                                                                    Short.MAX_VALUE))
                                            .addComponent(
                                                    count,
                                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    0, Short.MAX_VALUE))
                            .addContainerGap()));
    layout.setVerticalGroup(layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                    layout.createSequentialGroup()
                            .addContainerGap(
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE)
                            .addGroup(
                                    layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(serieLabel)
                                            .addComponent(
                                                    serie,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(
                                    layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(styleLabel)
                                            .addComponent(styleLine)
                                            .addComponent(styleFill)
                                            .addComponent(styleLineFill))
                            .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(
                                    layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(valueKindLabel)
                                            .addComponent(valueKind)
                                            .addComponent(deltaKind)
                                            .addComponent(meanKind)
                                            .addComponent(deltaMeanKind))
                            .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(value,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(
                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(count,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    90,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()));
  }// </editor-fold>//GEN-END:initComponents

  private void styleLineActionPerformed(java.awt.event.ActionEvent evt) // GEN-FIRST:event_styleLineActionPerformed
  {// GEN-HEADEREND:event_styleLineActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_styleLineActionPerformed

  private void valueKindActionPerformed(java.awt.event.ActionEvent evt) // GEN-FIRST:event_valueKindActionPerformed
  {// GEN-HEADEREND:event_valueKindActionPerformed
    count.setEnabled(false);
  }// GEN-LAST:event_valueKindActionPerformed

  private void meanKindActionPerformed(java.awt.event.ActionEvent evt) // GEN-FIRST:event_meanKindActionPerformed
  {// GEN-HEADEREND:event_meanKindActionPerformed
    count.setEnabled(true);
  }// GEN-LAST:event_meanKindActionPerformed

  private void deltaKindActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_deltaKindActionPerformed
  {// GEN-HEADEREND:event_deltaKindActionPerformed
    count.setEnabled(false);
  }// GEN-LAST:event_deltaKindActionPerformed

  private void deltaMeanKindActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_deltaMeanKindActionPerformed
  {// GEN-HEADEREND:event_deltaMeanKindActionPerformed
    count.setEnabled(true);
  }// GEN-LAST:event_deltaMeanKindActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private ch.ivyteam.ivy.visualvm.mbeans.MBeanAttributeChooserPanel count;
  private javax.swing.JRadioButton deltaKind;
  private javax.swing.JRadioButton deltaMeanKind;
  private javax.swing.ButtonGroup kind;
  private javax.swing.JRadioButton meanKind;
  private javax.swing.JTextField serie;
  private javax.swing.JLabel serieLabel;
  private javax.swing.ButtonGroup style;
  private javax.swing.JRadioButton styleFill;
  private javax.swing.JLabel styleLabel;
  private javax.swing.JRadioButton styleLine;
  private javax.swing.JRadioButton styleLineFill;
  private ch.ivyteam.ivy.visualvm.mbeans.MBeanAttributeChooserPanel value;
  private javax.swing.JRadioButton valueKind;
  private javax.swing.JLabel valueKindLabel;

  // End of variables declaration//GEN-END:variables
  /* CHECKSTYLE:ON */
  @Override
  public void componentOpened() {
    // TODO add custom code on component opening
  }

  @Override
  public void componentClosed() {
    // TODO add custom code on component closing
  }

  void writeProperties(java.util.Properties p) {
    // better to version settings since initial version as advocated at
    // http://wiki.apidesign.org/wiki/PropertyFiles
    p.setProperty("version", "1.0");
    // TODO store your settings
  }

  void readProperties(java.util.Properties p) {
    String version = p.getProperty("version");
    // TODO read your settings according to their version
  }

}
