/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ch.ivyteam.ivy.visualvm.view.restwebservice;

import ch.ivyteam.ivy.visualvm.model.RESTWebServiceInfo;
import java.util.List;
import javax.swing.JTable;
import org.jdesktop.beansbinding.Binding;

/**
 *
 * @author ntnam
 */
public class RESTWebServiceErrorExecutionPanel extends AbstractRESTWebServiceExecutionPanel {
  

  /**
   * Creates new customizer RESTWebServiceErrorExecutionPanel
   */
  public RESTWebServiceErrorExecutionPanel(RESTWebServicesView view) {
    super(view);
    initComponents();
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the FormEditor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    fErrorExecutionInfos = new java.util.ArrayList<RESTWebServiceInfo>();
    lblEmpty = new javax.swing.JLabel();
    btnRefresh = new javax.swing.JButton();
    jSplitPane1 = new javax.swing.JSplitPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    tableErrorExecution = new javax.swing.JTable();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtErrorDetail = new javax.swing.JTextArea();

    setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(lblEmpty, gridBagConstraints);

    btnRefresh.setText("Refresh");
    btnRefresh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRefreshActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(btnRefresh, gridBagConstraints);

    jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
    jSplitPane1.setBorder(null);
    jSplitPane1.setDividerLocation(200);
    jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

    org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, fErrorExecutionInfos, tableErrorExecution, "bindingErrorExecutionTable");
    org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${time}"));
    columnBinding.setColumnName("Time");
    columnBinding.setColumnClass(java.util.Date.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${webServiceConfig}"));
    columnBinding.setColumnName("Web Service Config");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${processElementId}"));
    columnBinding.setColumnName("Process Element Id");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${requestMethod}"));
    columnBinding.setColumnName("Request Method");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${responseStatus}"));
    columnBinding.setColumnName("Response Status");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${requestUrl}"));
    columnBinding.setColumnName("Request Url");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${errorMessage.message}"));
    columnBinding.setColumnName("Error Message");
    columnBinding.setColumnClass(String.class);
    columnBinding.setEditable(false);
    bindingGroup.addBinding(jTableBinding);
    jTableBinding.bind();
    jScrollPane1.setViewportView(tableErrorExecution);

    jSplitPane1.setTopComponent(jScrollPane1);

    txtErrorDetail.setColumns(20);
    txtErrorDetail.setRows(5);

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tableErrorExecution, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.errorDetail}"), txtErrorDetail, org.jdesktop.beansbinding.BeanProperty.create("text"), "bindingErrorExecutionMessage");
    bindingGroup.addBinding(binding);

    jScrollPane2.setViewportView(txtErrorDetail);

    jSplitPane1.setRightComponent(jScrollPane2);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(jSplitPane1, gridBagConstraints);

    bindingGroup.bind();
  }// </editor-fold>//GEN-END:initComponents

  private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    getRESTWebServicesView().refreshErrorExecutionTable();
  }//GEN-LAST:event_btnRefreshActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnRefresh;
  private java.util.ArrayList<RESTWebServiceInfo> fErrorExecutionInfos;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JLabel lblEmpty;
  private javax.swing.JTable tableErrorExecution;
  private javax.swing.JTextArea txtErrorDetail;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables

  @Override
  protected JTable getExecutionsTable() {
    return tableErrorExecution;
  }

  @Override
  protected void refreshQueriesTable(List<RESTWebServiceInfo> webServiceInfoList) {
    Binding binding = bindingGroup.getBinding("bindingErrorExecutionTable");
    binding.unbind();
    fErrorExecutionInfos.clear();
    fErrorExecutionInfos.addAll(webServiceInfoList);
    binding.bind();
    tableErrorExecution.repaint();
  }
}
