name: CI-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 8

    - name: Load Keystore
      id: load_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'keystore.jks'
        encodedString: ${{ secrets.KEYSTORE }}

    - name: Build with Maven
      run: mvn clean verify --batch-mode -P sign -Dcert.location=${{ steps.load_keystore.outputs.filePath }} -Dcert.keystorepw=${{ secrets.PASSWORD }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "target/surefire-reports/*.xml"

    - name: Keep build artifact
      uses: actions/upload-artifact@v2
      with:
        name: visualvm-plugin
        path: target/nbm/*.nbm
