name: Release-Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v4.5

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 8
        server-id: github

    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git checkout -b new-release

    - name: Load Keystore
      id: load_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'keystore.jks'
        encodedString: ${{ secrets.KEYSTORE }}

    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn --settings settings.xml -Darguments="-DaltDeploymentRepository=github::https://maven.pkg.github.com/axonivy-market/${{ github.event.repository.name }}" release:prepare release:perform --batch-mode -P sign -Darguments="-Dcert.keystorepw=${{ secrets.PASSWORD }} -Dcert.location=${{ steps.load_keystore.outputs.filePath }}"

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: ${{ steps.branch-name.outputs.current_branch }}
        source_branch: new-release
        pr_title: "Release"
        github_token: ${{ secrets.GITHUB_TOKEN }}
