name: Release-Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 8
        server-id: github

    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Load Keystore
      id: load_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'keystore.jks'
        encodedString: ${{ secrets.KEYSTORE }}

    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn release:prepare release:perform --batch-mode -P sign -Dcert.location=${{ steps.load_keystore.outputs.filePath }} -Dcert.password=${{ secrets.PASSWORD }}
